language: python

python:
  - "3.5"

addons:
  apt:
    packages:
      - pandoc
      - rubygems

before_install:
  - gem install sass

install: true

# command to run tests
script: python3 compileWebsite.py

notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f64888ca9e483f08d91f
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
