sudo: false # route your build to the container-based infrastructure for a faster build
language: ruby
rvm:
- 2.4.1

addons:
  apt:
    packages:
      - make
      - pandoc

before_install:
  - gem install jekyll bundler

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script:
  - make

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

# Deploy to gh-pages branch
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  local-dir: export
  on:
    branch: master

notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f64888ca9e483f08d91f
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
