# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Tex4Tum
email: info@latex4ei.de
description: > # this means to ignore newlines until "baseurl:"
  Interactive online knowledge base for engineers
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
collections:
  article:
    output: true
defaults:
  - scope:
      path: ""
      type: article
    values:
      layout: page
      permalink: /:name

# Build settings
markdown: Pandoc
kramdown:
  math_engine: mathjax
pandoc:
  flags: 'html5, latex_macros, implicit_figures'
  extensions:
    - normalize
    - smart
    - latexmathml
highlighter: pygments
gems:
  - bootstrap
  - autoprefixer-rails
  - jekyll-assets
  - jekyll-pandoc
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
